In [4]:
#1a
import numpy as np
arr=np.array([1,2,3,4,5])
print("after adding 2=",arr+2)
print("after multiplying with 3=",arr*3)
print("after dividing with 2=",arr/2)

after adding 2= [3 4 5 6 7]
after multiplying with 3= [ 3  6  9 12 15]
after dividing with 2= [0.5 1.  1.5 2.  2.5]


In [5]:
#2
import numpy as np
arr=np.array([1,2,3,6,4,5])
print("original array",arr)
print("reversed array",arr[:: -1])

original array [1 2 3 6 4 5]
reversed array [5 4 6 3 2 1]


In [11]:
#2ii
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,count=np.unique(x, return_counts=True)
most_freq=values[np.argmax(count)]
print(most_freq)

1


In [12]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
values,count=np.unique(y,return_counts=True)
most_freq=values[np.argmax(count)]
print(most_freq)

1


In [14]:
#3
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [17]:
#4
import numpy as np
Haritika=np.linspace(10,100,25)
print(Haritika)
print(Haritika.ndim)
print(Haritika.shape)
print(Haritika.size)
print(Haritika.dtype)
print(Haritika.nbytes)


transpose=Haritika.reshape(25,1)
print(transpose)

print(Haritika.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [18]:
#5
import numpy as np
ucs420_haritika=np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])
print(ucs420_haritika)
print(np.mean(ucs420_haritika))
print(np.median(ucs420_haritika))
print(np.max(ucs420_haritika))
print(np.min(ucs420_haritika))
print(np.unique(ucs420_haritika))

reshaped_ucs420_haritika=ucs420_haritika.reshape(4,3)
print(reshaped_ucs420_haritika)

resized_ucs420_haritika=np.resize(ucs420_Haritika, (2, 3))
print(resized_ucs420_haritika)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


NameError: name 'ucs420_Haritika' is not defined