In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add sensor error
corrected_temperature = temperature + 2
print("Corrected Temperature:", corrected_temperature)

# b. Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temperature + 32
print("Fahrenheit:", fahrenheit)

# c. Readings greater than 32°C
greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("Greater than 32°C:", greater_than_32)

# d. Count readings greater than 32°C
count = np.sum(corrected_temperature > 32)
print("Count:", count)

Corrected Temperature: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Greater than 32°C: [33 37 40 35 42]
Count: 5


In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a
print("Total:", np.sum(steps))

# b
print("Mean:", np.mean(steps))

# c
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))

# d
print("Total for each day:", np.sum(steps, axis=0))

# e
print("Total for each user:", np.sum(steps, axis=1))

# f
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Maximum position:", position)

Total: 84200
Mean: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total for each day: [26500 27300 30400]
Total for each user: [18300 24500 14400 27000]
Maximum position: (np.int64(3), np.int64(2))


In [3]:
import numpy as np

# a
original = np.array([1, 2, 3, 4, 5, 6])

# b
subset = original[1:4]

# c
subset[0] = 999
print("Original:", original)
print("Subset:", subset)

# d
copied = original[1:4].copy()
copied[0] = 500

print("Original:", original)
print("Copied:", copied)

# e
matrix = np.arange(1, 13).reshape(3, 4)
print("Matrix:")
print(matrix)

# f
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2, Columns 2-3:")
print(matrix[0:2, 1:3])

# g
flat1 = matrix.flatten()
flat2 = matrix.ravel()

print("Flatten:", flat1)
print("Ravel:", flat2)

# h
ravel_array = matrix.ravel()
ravel_array[0] = 100

print("After modifying ravel:")
print("Matrix:", matrix)

# i
flat_array = matrix.flatten()
flat_array[1] = 500

print("After modifying flatten:")
print("Matrix:", matrix)

# j
print("Shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("Size:", matrix.size)
print("dtype:", matrix.dtype)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4]
Original: [  1 999   3   4   5   6]
Copied: [500   3   4]
Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, Columns 2-3:
[[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel:
Matrix: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
After modifying flatten:
Matrix: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Shape: (3, 4)
ndim: 2
Size: 12
dtype: int64
